# HA-iDRAC/ha-idrac-controller/config.yaml

name: "HA iDRAC Controller BETA"
version: "0.1.0-dev.1" # Incremented version
slug: "ha_idrac_controller_Development"
description: "Control Dell iDRAC fan speeds and monitor server health in Home Assistant. Development Version. Not for production use."
arch:
  - "aarch64"
  - "amd64"
init: false
boot: "auto"

ingress: true
ingress_port: 8099
ingress_entry: "/"
panel_icon: "mdi:server-network"
panel_title: "iDRAC Control"
panel_admin: true

options:
  # Master Key for encrypting server credentials stored in /data/servers_config.json
  master_encryption_key: ""    # Secret

  # Default Fan Control Logic (can be overridden per server)
  temperature_unit: "C"
  base_fan_speed_percent: 20
  low_temp_threshold: 45
  high_temp_fan_speed_percent: 50
  critical_temp_threshold: 65

  # Polling and Logging
  check_interval_seconds: 30
  log_level: "info"

  # MQTT Configuration (Global for now)
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

schema:
  master_encryption_key: "password"

  # Default Fan Control Logic
  temperature_unit: "list(C|F)"
  base_fan_speed_percent: "int(0,100)"
  low_temp_threshold: "int(0,100)"
  high_temp_fan_speed_percent: "int(0,100)"
  critical_temp_threshold: "int(0,100)"

  # Polling and Logging
  check_interval_seconds: "int(5,)"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"

  # MQTT Configuration
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_username: "str?"
  mqtt_password: "password?"

map:
  - "data:rw"
hassio_role: "default"